site_name: Engenharia de Dados — Projeto Final

nav:
  - Início: index.md
  - Modelo MongoDB (origem): modelo_mongodb.md
  - MongoDB Atlas (compartilhado): mongodb_atlas.md
  - Ambiente Airflow: ambiente_airflow.md
  - Estrutura Landing: estrutura_landing.md
  - Estrutura Bronze: estrutura_bronze.md
  - Estrutura Silver: estrutura_silver.md
  - Estrutura Gold: estrutura_gold.md
  - DAG MongoDB para Landing: dag_mongodb_landing.md
  - DAG Landing para Bronze: dag_landing_bronze.md
  - DAG Bronze para Silver: dag_bronze_silver.md
